#pragma once
//パラメーター用のタグ
#define PARAM_FILTERFREQ_TAG 101
#define PARAM_FILTERQ_TAG 102
#define PARAM_FILTERTYPE_TAG 103

#define PARAM_POSTGAIN_TAG 991
#define PARAM_INV_TAG 992
#define PARAM_MIX_TAG 999